### ISSUE TITLE
[Playground] typo

### ISSUE THREAD

**Issue by prood** [modular/modular#109]
## Bug Description
Typo in HelloMojo.ipynb
-- Python translate directory
++ Python translate directly

What is the current, unexpected behavior?
Python translate directory
Please also include the expected behavior in your description.
Python translate directly

### Steps to Reproduce

1. 
2.

**Comment by lattner** [comment]
Mikhail fixed this; @ZolotukhinM plz close bugs when you merge fixes, thanks!
