### ISSUE TITLE
[Feature Request] Stack traceback of Mojo programs

### ISSUE THREAD

**Issue by ego** [modular/modular#140]
## Stack traceback of Mojo programs

One of the main features of Python is its excellent **error tracing** (unlike Java). Writing **code** starts with **debugging** **errors**, so it helps a lot if we have a good **error reporting system**.

### Motivation

```Mojo
error: Expression [11]:12:11: use of unknown declaration 'z'
    print(z)

let and var declarations also support type specifiers, patterns, and late initialization:
```

### Description and Requirements

Simple but helpful mechanism for errors like:

```shell
$ mojo example.mojo
Traceback (most recent call last):
  File "/path/to/example.mojo", line 4, in <module>
    hello('foo')
NameError: name 'bar' is not defined
```

with `stack/exc_type/filename/lineno/text/offset/msg/classmethod from_exception`.

Some notes about traceback in Python

https://realpython.com/python-traceback/
https://www.geeksforgeeks.org/traceback-in-python/

**Comment by walter-erquinigo** [comment]
Hi, thank you for request thing. This feature is in our roadmap and eventually we'll work on this.
