### ISSUE TITLE
[BUG] Unknown Variable Types (Int8 & Int64)

### ISSUE THREAD

**Issue by jspittman** [modular/modular#152]
## Bug Description

I tried to run code from the Mojo documentation (found here: https://docs.modular.com/mojo/programming-manual.html) within the Mojo playground.  The documentation states the use of the "Int8" and "Int64" variable types, however, the Mojo playground does not currently recognize these types.

### Steps to Reproduce

I replicated this in both a predefined Jupyter Notebook (HelloMojo.ipynb) and a custom created notebook.  Both instances returned the same error.

1) Input the following code:

def your_function():
    let x: Int8 = 42
    let y: Int64 = 17
​
    let z: Int8
    if x != 0:
        z = 1
    else:
        z = foo()
    use(z)

2) Run the notebook cell.

<img width="599" alt="Screenshot 2023-05-14 at 9 14 19 PM" src="https://github.com/modularml/mojo/assets/578603/210d4c38-091d-4ad5-ac0c-91a90db21e6a">

### Context

# MOJO CODE

def your_function():
    let x: Int8 = 42
    let y: Int64 = 17
​
    let z: Int8
    if x != 0:
        z = 1
    else:
        z = foo()
    use(z)

# RESULT

error: Expression [7]:6:12: use of unknown declaration 'Int8'
    let x: Int8 = 42
           ^~~~

error: Expression [7]:7:12: use of unknown declaration 'Int64'
    let y: Int64 = 17
           ^~~~~

error: Expression [7]:9:12: use of unknown declaration 'Int8'
    let z: Int8
           ^~~~

**Comment by czheo** [comment]
`Int8` `Int64` might not have been implemented yet.
Mojo now has integer types like `Int` `SI8` `SI64` `UI8` `UI64` and etc.

**Comment by sa-** [comment]
This should fix it
```python
def your_function():
    let x: SI8 = 42
    let y: Int = 17
​
    let z: SI8
    if x != 0:
        z = 1
    else:
        z = foo()
    use(z)
```

**Comment by lattner** [comment]
Indeed, as @czheo points out, these are currently named things like this in the SIMD module:

```
alias SI8 = SIMD[DType.si8, 1]
alias UI8 = SIMD[DType.ui8, 1]
alias SI16 = SIMD[DType.si16, 1]
alias UI16 = SIMD[DType.ui16, 1]
alias SI32 = SIMD[DType.si32, 1]
alias UI32 = SIMD[DType.ui32, 1]
alias SI64 = SIMD[DType.si64, 1]
alias UI64 = SIMD[DType.ui64, 1]

alias F8 = SIMD[DType.f8, 1]
alias F16 = SIMD[DType.f16, 1]
alias F32 = SIMD[DType.f32, 1]
alias F64 = SIMD[DType.f64, 1]
```

we aren't consistent here.  I also think the "SI8" names are also too arcane to be user-facing.  @abduld WDYT about renaming these to Int8/UInt8?

**Comment by survuvi** [comment]
I tried:

```python
from PythonInterface import Python

let np = Python.import_module("numpy")
alias SI8 = np.int8
```

_error: Expression [4]:6:13: use of unknown declaration 'np'
alias SI8 = np.int8_

**Comment by lattner** [comment]
Use this:

**Comment by czheo** [comment]
```py
alias SI8 = np.int8
```
@survuvi  I think the problem here is alias is a comptime statement but np is a runtime object, so you won't be able to access that. Also `np.int8` is not a Mojo type so I think you might not be able to alias here.

**Comment by abduld** [comment]
Renaming these to SI8 / UI8 / ... makes perfect sense in this case.
