### ISSUE TITLE
Official site blank

### ISSUE THREAD

**Issue by lucasjinreal** [modular/modular#16]
![image](https://user-images.githubusercontent.com/21303438/236115410-330395cf-e41a-4b8e-badb-2f97ee95e19a.png)

**Comment by iamtimdavis** [comment]
Thanks Lucas - can't reproduce that. Can you please give us some more details - modular.com/get-started is working. Also make sure to accept our cookies if you haven't already ?

**Comment by lucasjinreal** [comment]
@iamtimdavis does the website not accessable in China?

**Comment by goldiegadde** [comment]
@lucasjinreal can you try with a different browser and see if it works. No one has run into this issue, so I am inclined to close this one, but let us know, will keep it open for another day!
