### ISSUE TITLE
[Feature Request] Access modes for public and private access for modules or library access points

### ISSUE THREAD

**Issue by ksandvik** [modular/modular#207]
## Request

Provide protection for globals or function level for internal only access within the module or function. 

### Motivation

Python only protection is by coding style implementation as all symbols are always exported from modules. We need a way to hide internal state (globals) as well as internal only function implementations.

### Description and Requirements

Unlike C++, keep this simple, everything is public unless it's marked with a decorator @private or something similar.

**Comment by lattner** [comment]
Thank you for the suggestion, but we're focused on building out the core systems programming features per our roadmap.  There are a ton of "general goodness" features that oculd conceptually be added to Python, but it would be best to bring those up with the general PEP process right now.  We need to improve our FAQ to talk about this.  In any case, thank you for engaging with the mojo community!
