### ISSUE TITLE
Name clash with established open source project

### ISSUE THREAD

**Issue by genio** [modular/modular#8]
Hi,

Any chance you could rename this as it clashes with the Mojo framework that's been established for over 10 years now in Perl and more recently in Javascript as well?

Thanks,
Chase

**Comment by genio** [comment]
I'm aware of those other uses, but those aren't in the same realm as development environments, languages, or frameworks. A link to wikipedia on the topic is kind of a juvenile response when I'm being polite and asking nicely. You could have just said, "sorry, we're kind of stuck on the naming at this point" or some such.

**Comment by lattner** [comment]
I'm sorry I didn't mean to be flippant or grumpy about it!
