### ISSUE TITLE
[BUG] StringLiteral concat works only in narrow cases

### ISSUE THREAD

**Issue by akirchhoff-modular** [modular/modular#9]
Reported by @dom96 on Discord.

1. String literals do not persist across cells:

    Cell 1: `var x = "hello"`. 
    Cell 2: `print(x)`

    Expected result: "hello" printed  
    Actual result: Blank line printed

2. Concatenation with a string literal stored in a variable causes an error

    ```python
    var x = "Hello"
    print(x)
    print("hi" + x)
    ```

    Expected result: "hihello" printed  
    Actual result: Error: failed to legalize operation 'pop.string.concat' that was explicitly marked illegal

**Comment by Mogball** [comment]
We need to autopromote string literals to the `String` type, which properly supports runtime concatenation.

**Comment by Mogball** [comment]
Closing in favour of https://github.com/modularml/mojo/issues/100

**Comment by akirchhoff-modular** [comment]
@Mogball Is #100 sufficient to capture this? For example, it seems like `let x: StringLiteral = "hello"` and `print(x)` in separate cells should work, and would also have explicitly turned off auto-promotion so #100 would not be relevant. Am I missing something?

**Comment by Mogball** [comment]
Yes. StringLiteral.__add__ would have to promote to a `String`

**Comment by akirchhoff-modular** [comment]
I'm not talking about `__add__`, I'm talking just about having a `StringLiteral` variable in one cell and printing it in another. This is bullet point 1 in this issue -- I understand bullet point 2 is separate.

**Comment by Mogball** [comment]
Ah I see. That will probably not work in the notebook environment because string literals are pointers to static memory, which only lives as long as the jit'd object (I think). I'll file a new issue appropriately.

**Comment by akirchhoff-modular** [comment]
Sounds good. If you could, please link the new issue if you file it publicly (or send me the issue privately otherwise, please).

**Comment by Mogball** [comment]
https://github.com/modularml/mojo/issues/232
